facebook/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('img/', views.getImg, name='img'),
    path('documentations/', views.docsView, name='doc'),
    path('accounts', views.facebookAccountsView, name='facebookAccounts'),
    path('accounts/delete/<str:pk>/', views.deleteFbAccount, name='delete'),
    path('accounts/edite/<str:pk>/', views.EditFbAccountView, name='edite_fb'),
    path('groups/', views.groupsView, name='groups'),
    path('delete-group/<str:pk>/', views.deleteGroupView, name='del_groups'),
    path('start-compaign/', views.startCopmaignView, name='start_compaign'),
    path('checkaprovment/', views.checkIfGroupsApproved, name='checkaprovment'),
    path('images-galery/', views.imageGaleryView, name='images'),
    path('delete-images/<str:pk>/', views.deleteImg, name='delete_img'),
    path('adcopies/', views.adCopyView, name='adcopies'),
    path('delete-copy/<str:pk>/', views.deleteCopyWrite, name='delete_copy'),
    path('copy-write/', views.addCopyWriteView, name='copy_wirte'),
    path('delete-adcopies/<str:pk>/', views.deleteAdcopy, name='delete_adcopies'),
    path('edit-adcopies/<str:pk>/', views.EditAdCopyView, name='edit_adcopies'),
    path('addniche/', views.addNicheView, name='addniche'),
    path('deleteniche/<str:pk>/', views.deleteNiche, name='deleteniche'),
    path('check-Posted-Approved-And-Change-It-View/', views.checkPostedApprovedAndChangeItView, name='checkPostedApprovedAndChangeIt'),
    
]

home/urls.py
from django.urls import path
from . import views


urlpatterns = [
    path('', views.homeView, name='home'),
    path('login/', views.loginView, name='login'),
    path('logout/', views.logoutView, name='logout'),
    path('register/', views.registerView, name='register'),
    path('subscribe/', views.subscriptionView, name='subscription'),  
    path('add-coupon-code/', views.couponView, name='coupon'),  
    path('process_subscription/', views.process_subscription, name='process_subscription'),  
    path('payment_done/', views.payment_done, name='done'),
    path('you_canceled_payment/', views.you_canceled_payment, name='canceled'),
    path('activate/<str:uidb64>/<str:token>/', views.vereficationView, name='activate'),
    path('edit-settings/', views.editSettingsView, name='edit_settings'),
    path('profile/', views.prfileView, name='profile'),


]

main/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth import views as auth_views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include(('home.urls', 'home'), namespace = 'home')),
    path('support/', include('live_support.urls')),
    path('task-progress', include('celery_progress.urls')),
    path('facebook/', include(('facebook.urls', 'facebook'), namespace = 'fb')),
    path('dashboard/', include(('dashboard.urls','dashboard'),namespace='dash')),
    path('paypal/', include('paypal.standard.ipn.urls')),
    path('resetpassword/',auth_views.PasswordResetView.as_view(template_name='home/reset.html'), name='reset_password'),
    path('resetpasswordsent/',auth_views.PasswordResetDoneView.as_view(template_name='home/resetsent.html'), name='password_reset_done'),
    path('resetpassword/<uidb64>/<token>/',auth_views.PasswordResetConfirmView.as_view(template_name='home/resetconf.html'), name='password_reset_confirm'),
    path('resetpasswordcompete/',auth_views.PasswordResetCompleteView.as_view(template_name='home/resetcomplete.html'), name='password_reset_complete'),
    path('celery-progress/', include('celery_progress.urls')),

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

facebook/forms.py
from django import forms
from .models import adCopy, fbAccountsModel

class editAdCopyForm(forms.ModelForm):
    descriprtion = forms.CharField(widget=forms.Textarea(attrs={"row":"4","class":"w-100"}))
    link = forms.CharField(widget=forms.TextInput(attrs={"class":"w-100"}))
    image = forms.CharField(widget=forms.TextInput(attrs={"class":"w-100"}), required=False)

    class Meta :
        model = adCopy
        fields = ('descriprtion','link','image')

class editFbAccountForm(forms.ModelForm):
    fullname = forms.CharField(widget=forms.TextInput(attrs={"class":"w-100"}))
    class Meta :
        model = fbAccountsModel
        fields = ('fullname',)

facebook/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse
from django.contrib import messages
from .models import (
    fbAccountsModel, 
    myGroupsModel, 
    nichesModel,
    imageGalery,
    adCopy,
    copyWriting,
    postedAdCompaigns,
    settingModel,
    adminCopywrits,
    Docs
    )
from django.contrib.auth.models import User
from home.models import settingModel2
from home.models import profile, subscription
from django.core.exceptions import ObjectDoesNotExist
from django.utils import timezone
from django.contrib.auth.decorators import login_required
from .forms import editAdCopyForm, editFbAccountForm
from selenium import webdriver
from selenium.webdriver.common.keys import Keys
from requests.compat import quote_plus
from selenium.common.exceptions import (
    NoSuchWindowException, 
    NoSuchElementException, 
    StaleElementReferenceException,
    WebDriverException,
    )
from selenium.webdriver.common.action_chains import ActionChains
from .scripts import getDriver, generateCode
from django.contrib.auth.models import User
from .tasks import (
    joinGroupsTask,
    checkIfGroupsApprovedTask,
    StartCompaignTask,
    checkPostedApprovedAndChangeItTask
    )
import random, string, re , os, time
# Create your views here.

def getImg(request):
    img = imageGalery.objects.all()
    the_img = img[0].image.name
    chrome_options = webdriver.ChromeOptions()
    prefs = {"profile.default_content_setting_values.notifications" : 2}
    chrome_options.add_experimental_option("prefs",prefs)
    driver = None

    # try to find the chromdriver in local machin for linux
    try:
        driver = webdriver.Chrome('facebook/static/facebook/chrom/chromedriver', chrome_options=chrome_options)
        driver.get('https://imgbb.com/')
    except :
         try:
            driver = webdriver.Chrome('facebook/static/facebook/chrom/chromedriver1', chrome_options=chrome_options)
            driver.get('https://imgbb.com/')
         except :
            try:
                driver = webdriver.Chrome('facebook/static/facebook/chrom/chromedriver2', chrome_options=chrome_options)
                driver.get('https://imgbb.com/')
            except:
                pass

    upload = None
    while upload == None:
        try:
            upload = driver.find_element_by_id('anywhere-upload-input')
        except:
            upload = None
            print('none')
    upload.send_keys(the_img)
    print(f' this is path {the_img}')

    return HttpResponse("<h1>it worked</h1>") 

def docsView(request):
    doc = Docs.objects.all()
    if len(doc) < 1:
        return redirect('dashboard:dashboard')
    context = {
        'doc':doc[0],
        'title':'documentation'
    }
    return render(request, 'facebook/docs.html', context)

def is_valid(username, password):
    return username != '' and password != ''



@login_required
def facebookAccountsView(request):
    try :
        try:
            try:
                now = timezone.now()
                user = request.user
                my_profile = profile.objects.get(user = user)
                if my_profile.profile_subscription and my_profile.profile_subscription.paid == True and my_profile.subscription_status == 'active':
                    if my_profile.profile_subscription.subscription_to > now :
                    
                        fb_accounts = fbAccountsModel.objects.filter(user = request.user, accountStatus = 'active')
                        fb_accounts_to_show = fbAccountsModel.objects.filter(user = request.user)
                        print(fb_accounts)
                        if request.method == 'POST':
                            username = request.POST['username']
                            password = request.POST['password']
                            if username in fb_accounts :
                                messages.warning(request, 'this account is alredy added')
                                return redirect('/facebook/accounts')
                            else:
                                if is_valid(username, password):
                                    chrome_options = webdriver.ChromeOptions()
                                    chrome_options.binary_location = os.environ.get("GOOGLE_CHROME_BIN")
                                    chrome_options.add_argument('headless')
                                    chrome_options.add_argument("--disable-dev-shm-usage")
                                    chrome_options.add_argument("--no-sandbox")
                                    prefs = {"profile.default_content_setting_values.notifications" : 2}
                                    chrome_options.add_experimental_option("prefs",prefs)
                                    driver = None

                                    # try to find the chromdriver in local machin for linux
                                    try:
                                        driver = webdriver.Chrome('facebook/static/facebook/chrom/chromedriver', chrome_options=chrome_options)
                                        driver.get('https://www.facebook.com')
                                    except :
                                        try:
                                            driver = webdriver.Chrome('facebook/static/facebook/chrom/chromedriver1', chrome_options=chrome_options)
                                            driver.get('https://www.facebook.com')
                                        except :
                                            try:
                                                driver = webdriver.Chrome('facebook/static/facebook/chrom/chromedriver2', chrome_options=chrome_options)
                                                driver.get('https://www.facebook.com')
                                            except :
                                                # END try to find the chromdriver in local machin for linux

                                                # try to find the chromdriver in local machin for windows

                                                # END try to find the chromdriver in local machin for windows

                                                # then if did not find it run the one on heroku 
                                                try:
                                                    driver = webdriver.Chrome(executable_path=os.environ.get("CHROMEDRIVER_PATH"),chrome_options=chrome_options)
                                                    driver.get('https://www.facebook.com')
                                                except :                
                                                    return redirect('dashboard:dashboard')
                                                
                                    email = driver.find_element_by_id('email')
                                    fb_password = driver.find_element_by_id('pass')
                                    time.sleep(5)
                                    
                                    for item in username:
                                        email.send_keys(item)
                                    time.sleep(1)
                                    for item in password:
                                        fb_password.send_keys(item)
                                    fb_password.send_keys(Keys.RETURN)
                                    time.sleep(1)
                                    if 'https://www.facebook.com/checkpoint' in driver.current_url or 'https://www.facebook.com/checkpoint/?next' in driver.current_url:
                                        driver.close()
                                        messages.warning(request, 'this account is blocked')
                                        return redirect('fb:facebookAccounts')
                                    else:
                                        pass
                                    try:
                                        error_box = driver.find_element_by_id('error_box')
                                        driver.close()
                                        messages.warning(request, 'username or password is incorrect')
                                        return redirect('/facebook/accounts')
                                    except:
                                        driver.get('https://www.facebook.com/me/')
                                        time.sleep(1)
                                        try:
                                            old_facebook_version = driver.find_element_by_tag_name('h1').text
                                            if old_facebook_version == 'facebook' or old_facebook_version == 'فيسبوك' :
                                                driver.close()
                                                messages.warning(request, 'the facebook account you are trying to add is using the old version of facebook so please turn it to new version')
                                                return redirect('fb:facebookAccounts')
                                        except:
                                            pass
                                        fullname = None
                                        try:
                                            fullname = driver.find_element_by_xpath('//*[@id="mount_0_0"]/div/div[1]/div[1]/div[3]/div/div/div[1]/div[1]/div/div/div[1]/div[2]/div/div/div[2]/div/div/div[1]')
                                        except:
                                            pass
                                        time.sleep(2)
                                        datOfJoin = None
                                        try:

facebook/templates/facebook/EditAdcopy.html
{% extends 'dashboard/index.html' %}
{% load static %}
{% block content %}
<link rel="stylesheet" href="{% static 'facebook/css/style.css' %}">

<div class="dashboard-ecommerce">
    <div class="container-fluid dashboard-content ">
            <h3>Ad copies</h3>
           
        <div class="container">
                  <!-- load -->
     
                    <!-- end load -->
            <div class="row bg-light mb-2 border addNewAccount" id="hide_section">
                <div class="col-md-3"></div>
                <div class="col-md-6">
                <div>
                    <form method='POST' enctype="multipart/form-data">{% csrf_token %}
                        <div class="des">
                            <label for="discription">Discription:</label><br>
                           {{form.descriprtion}}
                        </div>
                        
                        <div class="link">
                            <label for="link">Link:</label><br>
                            {{form.link}}

                        </div>
                        <div class="mt-3 niches">
                            <p><strong>Current niche :</strong>  <span class="text-warning">{{my_adcopies.niche}}</span></p>

                            <label for="niche">Choose a niche:</label>
                            <select name="niche" id="niche" style="height:39px; width: 100%;" required>
                                <option value="" disabled selected hidden>Please Choose...</option>
                                {% for niche in niches %}
                                <option value="{{niche}}">{{niche}}</option>
                                {% endfor %}
                            </select>
                        </div>
                      
                        <div class="image mt-3">
                            <label for="link">Image Path:</label><br>
                            {{form.image}}
                        </div>
                      
                        <input type="submit" value="Save" class=" btn btn-success mt-3" >

                    </form>
                    
                </div>
                <div id="addaccoutform">

                </div>
               </div>
            </div>

       

        
        </div>
    </div>
</div>
{% endblock %}

facebook/templates/facebook/EditFbAccount.html

{% extends 'dashboard/index.html' %}
{% load static %}
{% block content %}
<link rel="stylesheet" href="{% static 'facebook/css/style.css' %}">

<div class="dashboard-ecommerce">
    <div class="container-fluid dashboard-content ">
            <h3>Ad copies</h3>
           
        <div class="container">
                  <!-- load -->
     
                    <!-- end load -->
            <div class="row bg-light mb-2 border addNewAccount" id="hide_section">
                <div class="col-md-3"></div>
                <div class="col-md-6">
                <div>
                    <form method='POST' enctype="multipart/form-data">{% csrf_token %}
                        <div class="des">
                            <label for="discription">Fb account Full_name:</label><br>
                           {{form.fullname}}
                           {% if my_fb.accountStatus == 'banded from posting' %}
                           <div class="form-check">
                            <input type="checkbox" class="form-check-input" id="exampleCheck1" name='unbanded'>
                            <label class="form-check-label" for="exampleCheck1">Check me out if this account is recovered </label>
                          </div>
                           {% endif %}
                        </div>
                                            
                        <input type="submit" value="Save" class=" btn btn-success mt-3" >

                    </form>
                    
                </div>
                <div id="addaccoutform">

                </div>
               </div>
            </div>

       

        
        </div>
    </div>
</div>
{% endblock %}

facebook/templates/facebook/adcopy.html
{% extends 'dashboard/index.html' %}
{% load static %}
{% block content %}
<link rel="stylesheet" href="{% static 'facebook/css/style.css' %}">

<div class="dashboard-ecommerce">
    <div class="container-fluid dashboard-content ">
        <h3>Ad copies</h3>
          
        <div class="container">
                {% if my_adcopies %}
                <div class="row bg-light mb-2 border addNewAccount" id="hide_section">
                    <div class="col-md-12">
                        <h5 class="ml-2">Your Ad Copies</h5>

                        <div>
                        
                                
                            <div>
                            
                                {% for ad in my_adcopies  %}
                                <div class="gallery2">
                                    <div class="desc2">
                                        <a href="{% url 'fb:delete_adcopies' ad.id %}" class="text-danger float-right">Delete</a>
                                        {% if ad.used %}<span class="text-success">Published</span>{% else %}<span class="text-warning">Active</span>{% endif %}
                                        <a href="{% url 'fb:edit_adcopies' ad.id %}" class="text-secondary float-left">Edite</a>
                                    </div>
                                    <div class="p-3" style="overflow-wrap: break-word;"><a href="{{ad.link}}">{{ad.link}}</a></div>
                                    {% if ad.image %}
                                    <div class="image_path p-1" style="overflow-wrap: break-word;">{{img.image}}</div>
                                    {% else %}
                                    <img src="http://via.placeholder.com/600x400" alt="" width="600" height="400" >
                                    {% endif %}
                                    <div class="desc2 p-2"><span class="text-warning">description</span> : {{ad.descriprtion}} </div>
                                </div>
                                {% endfor %}
            
                            </div>
         
                            <div id="addaccoutform">
            
                            </div>
                       </div>
                    </div>
        
                
                </div>
                {% endif %}

            <div class="row bg-light mb-2 border addNewAccount" id="hide_section">
                <div class="col-md-3"></div>
                <div class="col-md-6">
                <div>
                    <h5>Add new ad copy</h5>
                    <form method='POST' enctype="multipart/form-data">{% csrf_token %}
                        <div class="des">
                            <label for="discription">Discription:</label><br>
                            <textarea class="w-100" maxlength="200" placeholder="put description here" name="discription" rows="4" ></textarea>
                        </div>
                        
                        <div class="link">
                            <label for="link">Link:</label><br>
                            <input class="w-100" type="text" name="link" placeholder="put link here" id="link">
                        </div>

                        <div class="image mt-3">
                            <label for="img" >Choose Picture</label>
                            <input class="w-100" type="text" name="img" placeholder="put image path here" id="img">
                            
                        </div>
                        <div class="mt-3 niches">
                            <label for="niche">Choose a niche:</label>
                            <select name="niche" id="niche" style="height:39px; width: 100%;" required>
                                <option value="" disabled selected hidden>Please Choose...</option>
                                {% for niche in niches %}
                                <option value="{{niche}}">{{niche}}</option>
                                {% endfor %}
                            </select>
                        </div>
                      
                        <input type="submit" value="Save" class=" btn btn-success mt-3" >

                    </form>
                    
                </div>
                <div id="addaccoutform">

                </div>
               </div>
        </div>

          
    </div>
</div>
{% endblock %}

facebook/templates/facebook/addnich.html
{% extends 'dashboard/index.html' %}
{% load static %}
{% block content %}
<link rel="stylesheet" href="{% static 'facebook/css/style.css' %}">

<div class="dashboard-ecommerce">
    <div class="container-fluid dashboard-content ">
            <h3>Add niche</h3>
            <div class="alert alert-info" role="alert" id="note" id="alert">
                <p><strong>Note:</strong> by default the tool will join all the groups that did not have questions to answer
                    and it will display to you at the end two list, one with all the groups that we joind and
                    other one with all the groups that need awnsers so you can awnser them by yourself or 
                    <strong>you can check join all the groups and skip awnsering questions</strong> </p>
            </div>
            
        <div class="container">
                  <!-- load -->
     
                    <!-- end load -->
            <div class="row bg-light mb-2 border addNewAccount" id="hide_section">
                <div class="col-md-3"></div>
                <div class="col-md-6">
                <div>
                    <button class="btn border" id="addnewaccount">Add A Niche</button>
                </div>
                <div id="addaccoutform">

                    <form method="POST"> {% csrf_token %}
                        <input type="text" placeholder="your nich" name="niche" required>
                        <input type="checkbox" id="join_all" name="join" >
                        <label for="join_all">join all the groups and skip awnsering questions</label><br>
                        <input type="submit" value="Add Niche" >
                    </form>


                </div>
               </div>
            </div>

            <div class="row bg-light mb-2 border addNewAccount " id="gourps_list">
                <div class="col-md-3 text-center"></div>
                <div class="col-md-6 text-center">
                    {% if niches %}
                    <p class="red">Your Niches</p>
                        <ol class="text-left"> 
                            {% for niche in niches %}
                            <li>{{niche.niche}} <a href="{% url 'fb:deleteniche' niche.id %}" class="float-right">Delete</a></li>
                            {% endfor %}
                        </ol>
                    {% endif %}
                </div>
           
            </div>

           
        </div>
    </div>
</div>
{% endblock %}

facebook/templates/facebook/checkgroupsstatus_downlaod.html
{% extends "dashboard/index.html" %}
{% load static %}
<link rel="stylesheet" href="{% static 'facebook/css/style.css' %}">
{% block content %}
<!-- Reset Form -->

<!-- Download Form -->
<div class="container text-center mt-3 mb-3 p-4 bg-light border" >
    <h3 class="text-left">Check Groups Status</h3>
	<div class="row" id="hide_section">  
		<div class="col-md-3"></div>
        <div class="col-md-6">
			<form action="{% url 'fb:checkaprovment' %}" method="post" style="display: inline;" >
						{% csrf_token %}
						<button class="btn border" type="submit" style="
							background: #7a80b4;
							color: white;
							width: 90%;
						" >
							<strong>Check Groups Status</strong>
						</button>
			</form>
        </div>
	</div>

	<!-- Download Status -->
	<div style="height: 120px;">
		{% block progress %}{% endblock progress %}
	</div>

</div>
{% endblock %}

facebook/templates/facebook/delete_ad_copy.html

{% extends 'dashboard/index.html' %}
{% load static %}
{% block content %}
<link rel="stylesheet" href="{% static 'facebook/css/style.css' %}">
<div class="alert alert-primary mt-2" role="alert">
    By deleting this ad copy you will delete all the ad campaigns attached with it from fb publisher database</div>
<div class="dashboard-ecommerce p-5">
    <p>You are about to delete this Ad copy : <strong class="text-warning">{{my_adcopies.link}}</strong></p>
    <form method ="POST">{% csrf_token %}
        <input type="submit" value="Delete" class="btn btn-danger border">
    </form>
    <a href="{% url 'fb:adcopies' %}" class="btn btn-warning border text-light">Go Back</a>
</div>
{% endblock %}

facebook/templates/facebook/delete_facebook.html

{% extends 'dashboard/index.html' %}
{% load static %}
{% block content %}
<link rel="stylesheet" href="{% static 'facebook/css/style.css' %}">
<div class="alert alert-primary mt-2" role="alert">
    By deleting this fb account you will delete all the groups attached with it from fb publisher database</div>
<div class="dashboard-ecommerce p-5">
    <p>You are about to delete this FB Account : <strong class="text-warning">{{fb_account.username}}</strong></p>
    <form method ="POST">{% csrf_token %}
        <input type="submit" value="Delete" class="btn btn-danger border">
    </form>
    <a href="{% url 'fb:facebookAccounts' %}" class="btn btn-warning border text-light">Go Back</a>
</div>
{% endblock %}

facebook/templates/facebook/deleteniche.html
{% extends 'dashboard/index.html' %}
{% load static %}
{% block content %}
<link rel="stylesheet" href="{% static 'facebook/css/style.css' %}">

<div class="dashboard-ecommerce p-5">
    <p>You are about to delete this niche : <strong class="text-warning">{{niche.niche}}</strong></p>
    <form method ="POST">{% csrf_token %}
        <input type="submit" value="Delete" class="btn btn-danger border">
    </form>
    <a href="{% url 'fb:addniche' %}" class="btn btn-warning border text-light">Go Back</a>
</div>
{% endblock %}

facebook/templates/facebook/groups_downlaod.html
{% extends "dashboard/index.html" %}
{% load static %}
<link rel="stylesheet" href="{% static 'facebook/css/style.css' %}">
{% block content %}
<!-- Reset Form -->

<!-- Download Form -->
<div class="container text-center mt-3 mb-3 p-4 bg-light border" >
	<h3 class="text-left">Facebook Groups</h3>
	<div class="row" id="hide_section">  
		<div class="col-md-3"></div>
        <div class="col-md-6">
			<form action="{% url 'fb:groups' %}" method="post" style="display: inline;" >
						{% csrf_token %}
						<button class="btn border" type="submit" style="
							background: #7a80b4;
							color: white;
							width: 90%;
						" >
							<strong>Start Join Groups</strong>
						</button>
			</form>
        </div>
	</div>

	<!-- Download Status -->
	<div style="height: 120px;">
		{% block progress %}{% endblock progress %}
	</div>

</div>
{% endblock %}

facebook/templates/facebook/posts_wiating_approvment_downlaod.html
{% extends "dashboard/index.html" %}
{% load static %}
<link rel="stylesheet" href="{% static 'facebook/css/style.css' %}">
{% block content %}
<!-- Reset Form -->

<!-- Download Form -->
<div class="container text-center mt-3 mb-3 p-4 bg-light border" >
	<h3 class="text-left">Posts Waiting Approvment</h3>
	<div class="row" id="hide_section">  
		<div class="col-md-3"></div>
        <div class="col-md-6">
			<form action="{% url 'fb:groups' %}" method="post" style="display: inline;" >
						{% csrf_token %}
						<button class="btn border" type="submit" style="
							background: #7a80b4;
							color: white;
							width: 90%;
						" >
							<strong>Check Posts Status</strong>
						</button>
			</form>
        </div>
	</div>

	<!-- Download Status -->
	<div style="height: 120px;">
		{% block progress %}{% endblock progress %}
	</div>

</div>
{% endblock %}

facebook/templates/facebook/startcampaign_downlaod.html
{% extends "dashboard/index.html" %}
{% load static %}
<link rel="stylesheet" href="{% static 'facebook/css/style.css' %}">
{% block content %}
<!-- Reset Form -->

<!-- Download Form -->
<div class="container text-center mt-3 mb-3 p-4 bg-light border" >
	<h3 class="text-left">Start Campaign</h3>
	<div class="row" id="hide_section">  
		<div class="col-md-3"></div>
        <div class="col-md-6">
			<form action="{% url 'fb:start_compaign' %}" method="post" style="display: inline;" >
						{% csrf_token %}
						<button class="btn border" type="submit" style="
							background: #7a80b4;
							color: white;
							width: 90%;
						" >
							<strong>Start Campaign</strong>
						</button>
			</form>
        </div>
	</div>

	<!-- Download Status -->
	<div style="height: 120px;">
		{% block progress %}{% endblock progress %}
	</div>

	{% block all_ad_compains %} {% endblock all_ad_compains %}

</div>
{% endblock %}