home/urls.py
from django.urls import path
from . import views


urlpatterns = [
    path('', views.homeView, name='home'),
    path('login/', views.loginView, name='login'),
    path('logout/', views.logoutView, name='logout'),
    path('register/', views.registerView, name='register'),
    path('subscribe/', views.subscriptionView, name='subscription'),  
    path('add-coupon-code/', views.couponView, name='coupon'),  
    path('process_subscription/', views.process_subscription, name='process_subscription'),  
    path('payment_done/', views.payment_done, name='done'),
    path('you_canceled_payment/', views.you_canceled_payment, name='canceled'),
    path('activate/<str:uidb64>/<str:token>/', views.vereficationView, name='activate'),
    path('edit-settings/', views.editSettingsView, name='edit_settings'),
    path('profile/', views.prfileView, name='profile'),


]

main/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth import views as auth_views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include(('home.urls', 'home'), namespace = 'home')),
    path('support/', include('live_support.urls')),
    path('task-progress', include('celery_progress.urls')),
    path('facebook/', include(('facebook.urls', 'facebook'), namespace = 'fb')),
    path('dashboard/', include(('dashboard.urls','dashboard'),namespace='dash')),
    path('paypal/', include('paypal.standard.ipn.urls')),
    path('resetpassword/',auth_views.PasswordResetView.as_view(template_name='home/reset.html'), name='reset_password'),
    path('resetpasswordsent/',auth_views.PasswordResetDoneView.as_view(template_name='home/resetsent.html'), name='password_reset_done'),
    path('resetpassword/<uidb64>/<token>/',auth_views.PasswordResetConfirmView.as_view(template_name='home/resetconf.html'), name='password_reset_confirm'),
    path('resetpasswordcompete/',auth_views.PasswordResetCompleteView.as_view(template_name='home/resetcomplete.html'), name='password_reset_complete'),
    path('celery-progress/', include('celery_progress.urls')),

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

home/models.py
from django.db import models
from django.contrib.auth.models import User
from django.utils import timezone
from django.db.models.signals import post_save

# Create your models here.


durations = (
    ('m' , 'month'),
    ('s', 'six months'),
    ('y', 'year'),
)
duration_unit = (
    ('M' , 'month'),
    ('D', 'day'),
    ('Y', 'Year')
)
def addMonthToStartDate():
    return timezone.now() + timezone.timedelta(days=30)

class Coupon(models.Model):
    code = models.CharField(max_length=10)
    number_of_used_limite = models.IntegerField(default=0)
    number_of_used = models.IntegerField(default=0)
    trying_period = models.IntegerField(default=0)
    duration_unite = models.CharField(max_length=1, choices=duration_unit, default='D')
    trying_period_price = models.IntegerField(default=0)
    valid_from = models.DateTimeField(default=timezone.now)
    valid_to = models.DateTimeField(auto_now_add=False)
    active = models.BooleanField(default=True)
    benifiters = models.ManyToManyField(User, blank=True, null=True,)

    def __str__(self):
        return self.code

class subscription(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    subscription_duration = models.CharField(max_length=1, choices=durations)
    subscription_from = models.DateTimeField()
    subscription_to = models.DateTimeField()
    paid = models.BooleanField(default=False)
    price = models.FloatField(default=12.49)

    def __str__(self):
        return f"{self.user.username}'s subscription "

    def get_total_cost(self):
        return self.price


class profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    subscription_status = models.CharField(max_length=20, default="unactive")
    profile_subscription = models.ForeignKey(subscription, on_delete=models.SET_NULL, null=True, blank=True)
    coupon_code = models.ForeignKey(Coupon, on_delete=models.SET_NULL, null = True, blank = True)



    def __str__(self):
        return f"{self.user.username}'s profile "

class settingModel2(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    group_join_per_time= models.IntegerField(default=6)
    post_per_time = models.IntegerField(default=6)
    to_wait_after_each_join = models.IntegerField(default=12)
    to_wait_after_each_post = models.IntegerField(default=12)

    def __str__(self):
        return f'{self.user.username} settings'



def creatProfile(sender, **kwargs):
    if kwargs['created']:
        profile.objects.create(user=kwargs['instance'])

post_save.connect(creatProfile, sender=User)


def creatSetting(sender, **kwargs):
    if kwargs['created']:
        settingModel2.objects.create(user=kwargs['instance'])

post_save.connect(creatSetting, sender=User)


home/forms.py
from django import forms
from .models import settingModel2
from django.contrib.auth.models import User

subscription_options = [
    ('1-month', '1-Month subscription ($12.49 USD/Mon)'),
    ('6-month', '6-Month subscription Save $10 ($10.82 USD/Mon)'),
    ('1-year', '1-Year subscription Save $25 ($10.40 USD/Mon)'),
]


class SubscriptionForm(forms.Form):
    plans = forms.ChoiceField(choices=subscription_options)

class settingsForm(forms.ModelForm):
    class Meta:
        model = settingModel2
        fields = ['group_join_per_time','post_per_time']


class profileForm(forms.ModelForm):
    class Meta:
        model = User
        fields = ['first_name','last_name','email','username','password']

home/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.models import User
from django.contrib import messages
from django.utils import timezone
from django.contrib.auth import authenticate , login, logout
from django.views.decorators.csrf import csrf_exempt
from django.conf import settings
from paypal.standard.forms import PayPalPaymentsForm
from django.urls import reverse
from .models import subscription, profile, settingModel2, Coupon
from facebook.models import settingModel
from django.utils import timezone
from django.contrib.auth.decorators import login_required
from .forms import SubscriptionForm, settingsForm
from django.core.mail import EmailMessage
from django.utils.encoding import force_bytes, force_text, DjangoUnicodeDecodeError
from django.utils.http import urlsafe_base64_encode, urlsafe_base64_decode
from django.contrib.sites.shortcuts import get_current_site
from .utils import token_gen

def addMonthToStartDate():
    return timezone.now() + timezone.timedelta(days=30)

def addSixMonthToStartDate():
    return timezone.now() + timezone.timedelta(days=183)

def addYearToStartDate():
    return timezone.now() + timezone.timedelta(days=365)


# Create your views here.

def homeView(request):

    return render(request, 'home/index.html', {'title':'Fb Publisher'})

def matchPass(pass1 , pass2):
    return pass1 == pass2

def registerView(request):
    if request.user.is_authenticated:
        return redirect('dash:dashboard')
    else:
        if request.method == 'POST':
            first_name = request.POST['fname']
            last_name = request.POST['lname']
            email = request.POST['email']
            username = request.POST['username']
            password1 = request.POST['password1']
            password2 =  request.POST['password2']

            
            if matchPass(password1, password2):
                new_user = User(
                    username = username,
                    first_name = first_name,
                    last_name = last_name ,
                    email = email ,
                )

                if len(password2) < 8 :
                    messages.warning(request, 'you password is too short ')
                    return redirect('home:register')
                
                try : 
                    User.objects.get(email=email)
                    messages.warning(request, 'this email is alredy exists')
                    return redirect('home:register')
                except:
                    pass
                
                try : 
                    User.objects.get(username=username)
                    messages.warning(request, 'this username is alredy exists')
                    return redirect('home:register')
                except:
                    pass


                new_user.set_password(password2)
                new_user.is_active = False
                new_user.save()
                print(password2)
                

                uidb64 = urlsafe_base64_encode(force_bytes(new_user.pk))
                domain = get_current_site(request).domain
                link = reverse('home:activate', kwargs={'uidb64':uidb64,'token':token_gen.make_token(new_user)})
                activate_url = f'http://{domain}{link}'

                email_body = f"hello {username} please use this link to verify your account {activate_url}"
                email = EmailMessage(
                    'Fb publisher activation email',
                    email_body,
                    'noreplay@fbpublisher.com',
                    [email,],
                )

                email.send(fail_silently=False)
                messages.success(request, "you've succesfully registerd, please check your inbox to verify your email and if you don't find the email in your inbox check spam folder too ")
                return redirect('home:home')
            else:
                messages.warning(request, 'passwords did not match')
                return redirect('home:register')

    context = {
        'title':'register'
    }

    return render(request, 'home/register.html', context)

def loginView(request):
    if request.user.is_authenticated:
        return redirect('dash:dashboard')
    else:
        if request.method == 'POST':
            username = request.POST['username']
            password = request.POST['password']
            user = authenticate(username=username, password=password)
            if user is not None:
                login(request, user)
                return redirect('/dashboard')
            else :
                messages.warning(request, 'wrong password or username')
                return redirect('home:login')

    context = {
        'title':'login'
    }

    return render(request, 'home/login.html', context)

def vereficationView(request, uidb64, token):
    pk = urlsafe_base64_decode(uidb64)
    new_user = User.objects.get(id = pk)
    new_user.is_active = True
    new_user.save()

    messages.success(request, 'thanks for verifiy your account')
    return redirect('home:login')

@login_required
def logoutView(request):
    if not request.user.is_authenticated:
        messages.success(request, 'you\'re not loged in')
        return redirect('home:home')
    else:
        logout(request)
        messages.success(request, 'you\'re loged out')
        return redirect('home:login')
        

@login_required
def subscriptionView(request):
    my_profile = profile.objects.get(user = request.user)
    if my_profile.profile_subscription and my_profile.profile_subscription.paid and my_profile.subscription_status == 'active' :
        messages.info(request, 'you have an active subscription')
        return redirect('dashboard:dashboard')
    if request.method == 'POST':
        f = SubscriptionForm(request.POST)
        if f.is_valid():
            request.session['subscription_plan'] = request.POST.get('plans')
            return redirect('home:process_subscription')
    else:
        f = SubscriptionForm()
    return render(request, 'home/subscription_form.html', locals())

@login_required
def process_subscription(request):
    my_profile = profile.objects.get(user = request.user)
    if my_profile.profile_subscription and my_profile.profile_subscription.paid and my_profile.subscription_status == 'active' :
        messages.info(request, 'you have an active subscription')
        return redirect('dashboard:dashboard')
    price = None
    paypal_dict = None
    superusers = User.objects.get(is_superuser=True)
    admin_settings = settingModel.objects.get(user=superusers)
    subscription_plan = request.session.get('subscription_plan')
    host = request.get_host()
    
    if subscription_plan == '1-month':
        price = admin_settings.monthly_price
        billing_cycle = 1
        billing_cycle_unit = "M"
        the_sub = subscription.objects.create(
            user = request.user,
            subscription_duration = 'm',
            subscription_from = timezone.now(),
            subscription_to = addMonthToStartDate(),
            price = price
        )
        
    elif subscription_plan == '6-month':
        price = admin_settings.six_mounths_price
        billing_cycle = 6
        billing_cycle_unit = "M"
        the_sub = subscription.objects.create(
            user = request.user,
            subscription_duration = 's',
            subscription_from = timezone.now(),
            subscription_to = addSixMonthToStartDate(),
            price = price
        )
    else:
        price = admin_settings.yearly_price
        billing_cycle = 1
        billing_cycle_unit = "Y"
        the_sub = subscription.objects.create(
            user = request.user,
            subscription_duration = 'y',
            subscription_from = timezone.now(),
            subscription_to = addYearToStartDate(),
            price = price

        )
    the_profile = profile.objects.get(user=request.user)
    the_profile.profile_subscription = the_sub
    the_profile.save()

    if the_profile.coupon_code and the_profile.coupon_code.active and request.user not in the_profile.coupon_code.benifiters.all():
        paypal_dict  = {
            "cmd": "_xclick-subscriptions",
            'business': settings.PAYPAL_RECEIVER_EMAIL,
            "a1": str(the_profile.coupon_code.trying_period_price),	# trial price
	        "p1": the_profile.coupon_code.trying_period, # trial duration of each unit (depends on unit)
            "t1": the_profile.coupon_code.duration_unite,  # duration unit ("M for Month"
            "a3": price,  # monthly price
            "p3": billing_cycle,  # duration of each unit (depends on unit)
            "t3": billing_cycle_unit,  # duration unit ("M for Month")
            "src": "1",  # make payments recur
            "sra": "1",  # reattempt payment on payment error
            "no_note": "1",  # remove extra notes (optional)
            'item_name': 'FB PUBLISHER',
            'custom': 1,     # custom data, pass something meaningful here
            "invoice": str(the_sub.id),
            'currency_code': 'USD',
            'notify_url': 'http://{}{}'.format(host,
                                            reverse('paypal-ipn')),
            'return_url': 'http://{}{}'.format(host,
                                            reverse('home:done')),
            'cancel_return': 'http://{}{}'.format(host,
                                                reverse('home:canceled')),
        }
    else:
        paypal_dict  = {
            "cmd": "_xclick-subscriptions",
            'business': settings.PAYPAL_RECEIVER_EMAIL,
            "a3": price,  # monthly price
            "p3": billing_cycle,  # duration of each unit (depends on unit)

home/templates/home/downlaod.html
{% extends "dashboard/index.html" %}
{% load static %}

{% block content %}
<!-- Reset Form -->
<a href="{% url 'home:mail' %}" role="button" class="btn btn-primary btn-lg btn-block" style="border-radius: 0px;"><b>RESET</b></a>

<!-- Download Form -->
<div class="container text-center" style="padding-top: 20px;">
	<form action="{% url 'home:mail' %}" method="post" style="display: inline;">
		{% csrf_token %}
		<button class="btn btn-primary" type="submit" style="width:120px;">
			<strong>Download</strong>
		</button>
	</form>
</div>

<!-- Download Status -->
<div class="container" style="padding-top: 20px;">
	<div class="card" style="height: 120px;">
		{% block progress %}{% endblock progress %}
	</div>
</div>
{% endblock %}

home/templates/home/edit_settings.html
{% extends 'dashboard/index.html' %}
{% load static %}
{% block content %}
    
<style>
    body{
    background:#eee;    
}
.widget-author {
  margin-bottom: 58px;
}
.author-card {
  position: relative;
  padding-bottom: 48px;
  background-color: #fff;
  box-shadow: 0 12px 20px 1px rgba(64, 64, 64, .09);
}
.author-card .author-card-cover {
  position: relative;
  width: 100%;
  height: 100px;
  background-position: center;
  background-repeat: no-repeat;
  background-size: cover;
}
.author-card .author-card-cover::after {
  display: block;
  position: absolute;
  top: 0;
  left: 0;
  width: 100%;
  height: 100%;
  content: '';
  opacity: 0.5;
}
.author-card .author-card-cover > .btn {
  position: absolute;
  top: 12px;
  right: 12px;
  padding: 0 10px;
}
.author-card .author-card-profile {
  display: table;
  position: relative;
  margin-top: -22px;
  padding-right: 15px;
  padding-bottom: 16px;
  padding-left: 20px;
  z-index: 5;
}
.author-card .author-card-profile .author-card-avatar, .author-card .author-card-profile .author-card-details {
  display: table-cell;
  vertical-align: middle;
}
.author-card .author-card-profile .author-card-avatar {
  width: 85px;
  border-radius: 50%;
  box-shadow: 0 8px 20px 0 rgba(0, 0, 0, .15);
  overflow: hidden;
}
.author-card .author-card-profile .author-card-avatar > img {
  display: block;
  width: 100%;
}
.author-card .author-card-profile .author-card-details {
  padding-top: 20px;
  padding-left: 15px;
}
.author-card .author-card-profile .author-card-name {
  margin-bottom: 2px;
  font-size: 14px;
  font-weight: bold;
}
.author-card .author-card-profile .author-card-position {
  display: block;
  color: #8c8c8c;
  font-size: 12px;
  font-weight: 600;
}
.author-card .author-card-info {
  margin-bottom: 0;
  padding: 0 25px;
  font-size: 13px;
}
.author-card .author-card-social-bar-wrap {
  position: absolute;
  bottom: -18px;
  left: 0;
  width: 100%;
}
.author-card .author-card-social-bar-wrap .author-card-social-bar {
  display: table;
  margin: auto;
  background-color: #fff;
  box-shadow: 0 12px 20px 1px rgba(64, 64, 64, .11);
}
.btn-style-1.btn-white {
    background-color: #fff;
}
.list-group-item i {
    display: inline-block;
    margin-top: -1px;
    margin-right: 8px;
    font-size: 1.2em;
    vertical-align: middle;
}
.mr-1, .mx-1 {
    margin-right: .25rem !important;
}

.list-group-item.active:not(.disabled) {
    border-color: #e7e7e7;
    background: #fff;
    color: #ac32e4;
    cursor: default;
    pointer-events: none;
}
.list-group-flush:last-child .list-group-item:last-child {
    border-bottom: 0;
}

.list-group-flush .list-group-item {
    border-right: 0 !important;
    border-left: 0 !important;
}

.list-group-flush .list-group-item {
    border-right: 0;
    border-left: 0;
    border-radius: 0;
}
.list-group-item.active {
    z-index: 2;
    color: #fff;
    background-color: #007bff;
    border-color: #007bff;
}
.list-group-item:last-child {
    margin-bottom: 0;
    border-bottom-right-radius: .25rem;
    border-bottom-left-radius: .25rem;
}
a.list-group-item, .list-group-item-action {
    color: #404040;
    font-weight: 600;
}
.list-group-item {
    padding-top: 16px;
    padding-bottom: 16px;
    -webkit-transition: all .3s;
    transition: all .3s;
    border: 1px solid #e7e7e7 !important;
    border-radius: 0 !important;
    color: #404040;
    font-size: 12px;
    font-weight: 600;
    letter-spacing: .08em;
    text-transform: uppercase;
    text-decoration: none;
}
.list-group-item {
    position: relative;
    display: block;
    padding: .75rem 1.25rem;
    margin-bottom: -1px;
    background-color: #fff;
    border: 1px solid rgba(0,0,0,0.125);
}
.list-group-item.active:not(.disabled)::before {
    background-color: #ac32e4;
}

.list-group-item::before {
    display: block;
    position: absolute;
    top: 0;
    left: 0;
    width: 3px;
    height: 100%;
    background-color: transparent;
    content: '';
}
</style>

<div class="container mt-5">
    <div class="row">
        <div class="col-lg-4 pb-5">
            <!-- Account Sidebar-->
            <div class="author-card pb-3">
                <div class="author-card-cover" style="background-image: url(https://demo.createx.studio/createx-html/img/widgets/author/cover.jpg);"><a class="btn btn-style-1 btn-white btn-sm" href="#" data-toggle="tooltip" title="" data-original-title="You currently have 290 Reward points to spend"><i class="fa fa-award text-md"></i>&nbsp;{{my_profile.subscription_status}}</a></div>
                <div class="author-card-profile">
                    <div class="author-card-avatar"><img src="{% static 'home/images/pi.png' %}" alt="user image">
                    </div>
                    <div class="author-card-details">
                        <h5 class="author-card-name text-lg">{{user.first_name}} {{user.last_name}}</h5>
                    
                        <span class="author-card-position"><strong>subscribe until</strong> : {{my_profile.profile_subscription.subscription_to}}</span>
                    </div>
                </div>
            </div>
            <div class="wizard">
                <nav class="list-group list-group-flush">
                    <a class="list-group-item " href="{% url 'home:profile' %}"><i class="fe-icon-user text-muted"></i>Profile Settings</a>
                    <a class="list-group-item active" href="{% url 'home:edit_settings' %}">
                        <div class="d-flex justify-content-between align-items-center">
                            <div><i class="fe-icon-shopping-bag mr-1 text-muted"></i>
                                <div class="d-inline-block font-weight-medium text-uppercase">Fb publisher Settings</div>
                            </div>
                        </div>
                    </a>
                </nav>
            </div>
        </div>
        <!-- Profile Settings-->
        <div class="col-lg-8 pb-5">
            <form class="row" method="POST">{% csrf_token %}

                <div class="col-md-6">
                    <div class="form-group">
                        <label for="account-fn">Groups to Join Per Time</label>
                        <input class="form-control" type="text" id="account-fn" name="groups_per_time" value="{{groups_per_time}}" required>
                    </div>
                </div>
                <div class="col-md-6">
                    <div class="form-group">
                        <label for="account-ln">Ads to Post Per Time</label>
                        <input class="form-control" type="text" id="account-ln" name="posts_per_time" value="{{posts_per_time}}" required>
                    </div>
                </div>
                <div class="col-md-6">
                    <div class="form-group">
                        <label for="account-fn">Wiat after each join ( in minutes )</label>
                        <input class="form-control" type="text" id="account-fn" name="to_wait_after_each_join" value="{{to_wait_after_each_join}}" required>
                    </div>
                </div>
                <div class="col-md-6">
                    <div class="form-group">
                        <label for="account-ln">Wiat after each post ( in minutes )</label>
                        <input class="form-control" type="text" id="account-ln" name="to_wait_after_each_post" value="{{to_wait_after_each_post}}" required>
                    </div>
                </div>
                
                <div class="col-12">
                    <hr class="mt-2 mb-3">
                    <div class="d-flex flex-wrap justify-content-between align-items-center">
                        <button class="btn btn-style-1 btn-primary" type="submit" data-toast="" data-toast-position="topRight" data-toast-type="success" data-toast-icon="fe-icon-check-circle" data-toast-title="Success!" data-toast-message="Your profile updated successfuly.">Update Settigs</button>
                    </div>
                </div>
            </form>
        </div>
    </div>
</div>

{% endblock %}

home/templates/home/login.html
{% extends 'home/main.html' %}
{% load static %}
{% block content %}
<div id="colorlib-contact">
    <div class="container">
        <h4><a href=" {% url 'home:home' %}" style="text-decoration: underline;">Go Back Home</a> </h4>
        <div class="row">
            <div class="col-md-2"></div>
            <div class="col-md-8 animate-box">
                <h2>Login To Your Account</h2>
                <form method="POST">{% csrf_token %}
                    <div class="row form-group">
                        <div class="col-md-6">
                            <!-- <label for="fname">First Name</label> -->
                            <input type="text" id="username" class="form-control" placeholder="Your username" name="username" required>
                        </div>
                        <div class="col-md-6">
                            <!-- <label for="lname">Last Name</label> -->
                            <input type="password" id="password" class="form-control" placeholder="Your password" style="height: 50px;" name="password" required>
                        </div>
                    </div>
                    <div class="form-group">
                        <div class="row">
                          
                            <div class="col-md-4">
                                <input type="submit" value="LOGIN" class="btn btn-primary" style="width: 100%;">
                            </div>
                        </div>

                    </div>
                    <span style="display: block;"><a href="{% url 'home:register' %}">Don't Have Account Register Now</a></span>
                    <span style="display: block;"><a href="{% url 'reset_password' %}">Forget my password</a></span>
                </form>		
            </div>
        </div>
    </div>
</div>

{% endblock %}

home/templates/home/main.html
{% load static %}

<!DOCTYPE HTML>
<html>
	<head>
	<meta charset="utf-8">
	<meta http-equiv="X-UA-Compatible" content="IE=edge">
	<title>{{title}}</title>
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<meta name="description" content="" />
	<meta name="keywords" content="" />
	<meta name="author" content="" />

  <!-- Facebook and Twitter integration -->
	<meta property="og:title" content=""/>
	<meta property="og:image" content=""/>
	<meta property="og:url" content=""/>
	<meta property="og:site_name" content=""/>
	<meta property="og:description" content=""/>
	<meta name="twitter:title" content="" />
	<meta name="twitter:image" content="" />
	<meta name="twitter:url" content="" />
	<meta name="twitter:card" content="" />
	<link rel="shortcut icon" type="image/png" href="{% static 'home/favicon/favicon.ico' %}"/>
	<link href="https://fonts.googleapis.com/css?family=Poppins:300,400,500,600" rel="stylesheet">
	<link href="https://fonts.googleapis.com/css?family=Nunito:200,300,400" rel="stylesheet">
	
	<!-- Animate.css -->
	<link rel="stylesheet" href="{% static 'home/css/animate.css' %} ">
	<!-- Icomoon Icon Fonts-->
	<link rel="stylesheet" href="{% static 'home/css/icomoon.css' %}  ">
	<!-- Bootstrap  -->
	<link rel="stylesheet" href="{% static 'home/css/bootstrap.css' %} ">

	<!-- Magnific Popup -->
	<link rel="stylesheet" href="{% static 'home/css/magnific-popup.css' %} ">

	<!-- Owl Carousel -->
	<link rel="stylesheet" href="{% static 'home/css/owl.carousel.min.css' %} ">
	<link rel="stylesheet" href="{% static 'home/css/owl.theme.default.min.css' %}">

	<!-- Theme style  -->
	<link rel="stylesheet" href=" {% static 'home/css/style.css' %}">

	<!-- Modernizr JS -->
	<script src=" {% static 'home/js/modernizr-2.6.2.min.js' %}  "></script>
	<!-- FOR IE9 below -->
	<!--[if lt IE 9]>
	<script src="js/respond.min.js"></script>
	<![endif]-->

	</head>
	<body>
{% if messages %}
	{% for message in messages %}
	<div class="alert alert-{{ message.tags }}" role="alert">
		{{ message }}
	</div>
    {% endfor %}
{% endif %}

        {% block content %}

        {% endblock %}

    	<!-- jQuery -->
	<script src="{% static 'home/js/jquery.min.js' %}"></script>
	<!-- jQuery Easing -->
	<script src="{% static 'home/js/jquery.easing.1.3.js' %} "></script>
	<!-- Bootstrap -->
	<script src="{% static 'home/js/bootstrap.min.js' %} "></script>
	<!-- Waypoints -->
	<script src="{% static 'home/js/jquery.waypoints.min.js' %} "></script>
	<!-- Stellar Parallax -->
	<script src="{% static 'home/js/jquery.stellar.min.js' %} "></script>
	<!-- YTPlayer -->
	<script src="{% static 'home/js/jquery.mb.YTPlayer.min.js' %} "></script>
	<!-- Owl carousel -->
	<script src="{% static 'home/js/owl.carousel.min.js' %} "></script>
	<!-- Magnific Popup -->
	<script src="{% static 'home/js/jquery.magnific-popup.min.js' %} "></script>
	<script src="{% static 'home/js/magnific-popup-options.js' %} "></script>
	<!-- Counters -->
	<script src="{% static 'home/js/jquery.countTo.js' %} "></script>
	<!-- Main -->
	<script src="{% static 'home/js/main.js' %} "></script>

	</body>
</html>

home/templates/home/progress.html
{% extends "home/downlaod.html" %}
{% load static %}
{% block progress %}
<div class="text-center" style="font-size: 14px">
	<div id="progress-bar-message">
	Click the "Download" button
	</div>
</div>
<div class='progress-wrapper' style="padding-top: 10px;">
  <div id='progress-bar' class='progress-bar progress-bar-striped' role='progressbar' style="height:30px; width: 0%; border-radius: 5px">&nbsp;</div>
</div>
<div id="celery-result">
</div>
{% endblock progress %}

{% block progress_bar_js %}
{% if task_id %}
<script type="text/javascript">
	// Progress Bar (JQuery)
	$(function () {
		var progressUrl = "{% url 'celery_progress:task_status' task_id %}";
		CeleryProgressBar.initProgressBar(progressUrl, {})
	});
</script>
{% endif %}
{% endblock progress_bar_js %}

home/templates/home/select_plane.html
{% extends "dashboard/index.html" %}
{% block title %}Subscribe{% endblock %}
{% block content %}
<style>
    input[type="submit"] {
        width: 200px;
        height: 50px;
        color: white;
        background: #0e0c28;
        outline: none;
        border: none;
    }
    select#id_plans {
        height: 50px;
        border: none;
        border-bottom: 1px solid;
        background: none;
        outline: none;
    }
</style>
<div class="row">
    <div class="col-md-1">
        
    </div>
    <p class="mt-2">CHOOSE A PLAN</p>
</div>
<div class="row">
        <div class="col-md-4">
            
        </div>
        <div class="col-md-6 mt-5 mb-5">
            <form action="" method="post">
                {% csrf_token %}
                
                {{ f.plans }}
                <div class="mt-2">
                    <input type="submit" value="Subscribe">
                </div>
            </form>
        </div>
</div>
   

    
{% endblock %}

home/templates/home/settings.html
{% extends 'dashboard/index.html' %}
{% load static %}
{% block content %}
    
{% endblock %}